sudo: required
services:
  - docker

os:
  - linux
language: node_js
node_js:
  - '8'
  - '10'

notifications:
  email:
    on_success: never

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn ci
  - yarn global add codecov
after_success:
  - codecov
